### ISSUE TITLE
[FP] SLABS FALSE POSITIVE (PHASE)

### ISSUE THREAD

**Issue by artemati1** [jiangdashao/Matrix-Issues#367] opened 2019-05-04 19:08 UTC
## Troubleshooting Information

- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, or 1.14 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: spigot 1.8.8
**Verbose messages**: video
**How/when does this happen**: video 
**Video of false positive**: https://yadi.sk/i/RlMhze7_CfT8sQ
**Other information**: my nick is artemati

## Configuration Files
**checks.yml file**: default
**config.yml file**: default

**Comment by ignPerformance** [comment] 2019-05-04 23:22
Duplicate of #362.

**Closed by ignPerformance** 2019-05-04 23:22 UTC
Labels: False Positive
