### ISSUE TITLE
[FP] Speed player run into a closed door

### ISSUE THREAD

**Issue by zikdriver** [jiangdashao/Matrix-Issues#1723] opened 2020-05-30 10:05 UTC
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [ x] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper1.8.8
**Verbose messages**: https://i.imgur.com/VFsRGNT.png

**How/when does this happen**: 
**Video of false positive**: 
**Other information**: The person tried to open a closed door and ran into the door.

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment] 2020-05-31 03:30
Please record a video to show how to reproduce the false positive

**Comment by zikdriver** [comment] 2020-05-31 12:34
https://www.youtube.com/watch?v=Jf70ry4fmL4&feature=youtu.be Here.
And then I made the speed check off But then the player was detected for FastHeal

**Comment by jiangdashao** [comment] 2020-06-03 02:24
Can you reproduce the false positive by your self?

**Comment by jiangdashao** [comment] 2020-06-03 02:25
I can't reproduce this false positive. I guess it is opening and closing frequently?

**Closed** 2020-06-04 07:56 UTC
Labels: Can't Reproduce, False Positive, Insufficient Info
