### ISSUE TITLE
[BYPASS] Speed bypass

### ISSUE THREAD

**Issue by rasputinea** [jiangdashao/Matrix-Issues#1367] opened 2020-02-14 22:21 UTC
**Server version**: 1.15.2
**Hacked client**: WWE
**Cheat that bypassed**: speed
**Video of bypass**: https://youtu.be/JikQAe8S9Tc
**Other information**: make sure to use <1.02 modifier, timer doesnt matter. Also make sure you aren't moving before you toggle it off.

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by jiangdashao** [comment] 2020-02-15 08:04
Caused by Minecraft's shit built-in anti-cheat, it prevents calling the movement event if players moving too fast.

**Closed by jiangdashao** 2020-02-15 08:04 UTC
Labels: Bypass

**Comment by rasputinea** [comment] 2020-02-15 10:57
Dont use playermoveevent then? Can't that be disabled by clients that teleport the player to the void?

**Comment by jiangdashao** [comment] 2020-02-15 10:58
I will automatically modify the Spigot Config to disable the built-in anti cheat in the next version
