### ISSUE TITLE
[BYPASS] Speed

### ISSUE THREAD

**Issue by Maxsimuss** [jiangdashao/Matrix-Issues#1585] opened 2020-04-06 18:23 UTC
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15 server
- [X] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Hacked client**: LiquidBounce 1.12.2
**Link to hacked client**: https://liquidbounce.net/download
**Cheat that bypassed**: Custom Speed S0.8 Y1.0 T1.0
**Video of bypass**: https://youtu.be/yTAXPiL3QYU
**Other information**: Speed 0.8, Y 1.0, Timer 1.0, CustomStrafe true

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by ooodlllars** [comment] 2020-04-06 23:17
this isnt even a bypass you're using the elytra

**Comment by jiangdashao** [comment] 2020-04-07 09:04
caused by Elytra, I won't fix it

**Closed by jiangdashao** 2020-04-07 09:04 UTC
Labels: Bypass
