### ISSUE TITLE
[FP] FastBreak

### ISSUE THREAD

**Issue by FallenEmo** [jiangdashao/Matrix-Issues#1384] opened 2020-02-17 17:47 UTC
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14 or 1.15 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.15.2
**Verbose messages**: Keeps saying that they use FastBreak
**How/when does this happen**: The check is telling me that people in my server uses Fastbreak on default checks.yml
**Video of false positive**: I disabled already because was keep kicking players out
**Other information**: none

## Configuration Files
**Link to checks.yml file**: Default

**Comment by rasputinea** [comment] 2020-02-17 22:26
likely a duplicate of #1379

**Closed** 2020-02-18 12:52 UTC
Labels: False Positive
