### ISSUE TITLE
[INCOMPATIBILITY] WorldGuard

### ISSUE THREAD

**Issue by ignPerformance** [jiangdashao/Matrix-Issues#281] opened 2019-04-23 21:48 UTC
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, or 1.13 server
- [X] The issue happens on default config.yml and checks.yml

## Issue Information
**Server version**: 1.13.2
**Verbose messages/errors**: Watch the video.
**How/when does this happen**: When you jump and place a block underneath you or in front of you, or break a block under you like a Lilypad on protected land.
**Video of false positive**: https://1drv.ms/v/s!ApY4tKsF8vPUgpFT2rrBngtq1mMgdg
https://1drv.ms/v/s!ApY4tKsF8vPUgpFUjyY8ohqL91VI-g
**Other information**: WorldGuard has available API documentation to fix this issue.

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by True-cc** [comment] 2019-04-24 01:29
It's not a false that can be fixed because the blocks are only there client side, not server side.

**Comment by ignPerformance** [comment] 2019-04-24 01:29
Good way to get banned though. GG.

**Comment by jiangdashao** [comment] 2019-04-24 05:14
I won't fix these false positives caused by other protection plugins.

**Comment by ignPerformance** [comment] 2019-04-24 05:15
Can you at least look through WorldGuard's API? https://worldguard.enginehub.org/en/latest/developer/

**Comment by ignPerformance** [comment] 2019-04-24 05:16
https://bukkit.org/threads/check-if-a-player-is-in-a-protected-area.76918/

**Comment by ignPerformance** [comment] 2019-04-24 05:16
I can foreshadow _a lot_ of players getting banned because of protected blocks.

**Comment by jiangdashao** [comment] 2019-04-24 05:17
I don't want to insert any hooking code with other plugins in Matrix
And, this bug also can be found in AAC/NCP

**Comment by ignPerformance** [comment] 2019-04-24 05:18
Leave this issue open please. It's still an ongoing false positive, just tag it as Won't Fix.

**Comment by ignPerformance** [comment] 2019-04-24 05:23
Also, this issue is fixed on Spartan.

**Comment by ignPerformance** [comment] 2019-04-27 22:21
Here's an insane false positive: https://youtu.be/FIrk5rOs9Eo

**Closed** 2019-05-16 13:46 UTC
Labels: Critical, Incompatibility
