### ISSUE TITLE
[FP]  Elytra Fly + rockets

### ISSUE THREAD

**Issue by NyannyWu** [jiangdashao/Matrix-Issues#236] opened 2019-04-15 03:30 UTC
## Basic Information
**Verbose message(s)**:  https://hastebin.com/raw/gayagujelo
**How/when does this happen**:  Flying with elytras+rockets
**Video of false positive**:   https://streamable.com/b4ouq

## Configuration Files
**Link to checks.yml file**:  https://hastebin.com/raw/okufizecoh
**Link to config.yml file**:  https://hastebin.com/raw/rumivuruki

# Server Infomation
**Server Version**:  1.13.2
**Matrix Version**:  1.8.9
**ProtocolLib Version**: 4.4.0

**Comment by ignPerformance** [comment] 2019-04-15 03:35
Duplicate of #198

**Closed** 2019-04-15 03:36 UTC
Labels: Duplicate, False Positive
