### ISSUE TITLE
Problems when flying on the elytra with fireworks or building pillars.

### ISSUE THREAD

**Issue by bloodyearth** [jiangdashao/Matrix-Issues#6] opened 2019-02-11 09:47 UTC
Hey. I downloaded the latest version of the plugin, but I have some problems with it.

For example, if I use fireworks when flying on the elytra, then after some time I teleport back to the place where I started the flight.

The second problem is that if I build a pillar, then it starts pushing me from it.

However, I do not observe any messages in the chat or console.

**Comment by jiangdashao** [comment] 2019-02-11 14:49
1.  You should use "/matrix verbose" command to enable the output message
2. Please record a video with the verbose message output enabled to report the false positives, because I can't reproduce the bugs

**Comment by bloodyearth** [comment] 2019-02-11 18:57
> 1. You should use "/matrix verbose" command to enable the output message
> 2. Please record a video with the verbose message output enabled to report the false positives, because I can't reproduce the bugs

This is when flying on elytra: 
https://ibb.co/2cG2YnK

And this is after teleporting back when flying:
https://ibb.co/Tc18YCg

I'll record the video later, now there is no possibility.

**Comment by bloodyearth** [comment] 2019-02-11 19:04
This is when building pillars:
https://ibb.co/KLqFnF6

**Comment by jiangdashao** [comment] 2019-02-12 00:42
The "step-r" and "step-1" false positive should be fixed in the next update.
But the "BadPackets" false positives when flying on elytra was caused by server lagging, you TPS was dropped to 18.x

**Comment by bloodyearth** [comment] 2019-02-12 08:32
And this can not be fixed?

**Comment by jiangdashao** [comment] 2019-02-12 10:59
I need some time to improve this check, but not now, because doing a good BadPackets check is very troublesome.

**Comment by bloodyearth** [comment] 2019-02-12 11:13
okay

**Comment by jiangdashao** [comment] 2019-02-12 12:06
I developed a new BadPackets check that will be more responsive and less false positives.
You can try it in the next update!!

**Comment by bloodyearth** [comment] 2019-02-12 16:44
Ok, i try it.

**Closed** 2019-02-13 14:15 UTC
Labels: Bug, False Positive
