### ISSUE TITLE
[FP] Step into fences

### ISSUE THREAD

**Issue by masterstreamer** [jiangdashao/Matrix-Issues#248] opened 2019-04-17 13:40 UTC
## Basic Information
**Verbose message(s)**: is phase into block (Phase)
**How/when does this happen**: 
By jumping onto a triangle of fences you get a false positive and get kicked
**Screenshot**: https://imgur.com/a/asG6gWE

# Server Infomation
**Server Version**: 1.13.2

**Comment by jiangdashao** [comment] 2019-04-17 13:46
Please provide video evidence

**Comment by masterstreamer** [comment] 2019-04-17 13:57
@jiangdashao Alright, see here: https://drive.google.com/file/d/1z0LxFV5zL041nku7fI2Q0VVqdOAFcTSF/view?usp=sharing

**Comment by ignPerformance** [comment] 2019-04-17 18:31
Duplicate of #169.

**Closed by ignPerformance** 2019-04-17 18:31 UTC
Labels: False Positive

**Comment by masterstreamer** [comment] 2019-04-18 06:12
@ignPerformance No, it isn't duplicate. walking on side of a fence works fine, only as shown in my video there is a false positive. btw, walls are not causing this.

**Comment by ignPerformance** [comment] 2019-04-18 06:18
Walking in between an intersect of 3 fences, I know. Same with cobblestone walls.
